#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Tool
#
VERSION = 0.1
PACKAGE_NAME = opensn0w
TOOL_NAME = opensn0w
opensn0w_TOOL_ICON = 


#
# Resource files
#
opensn0w_RESOURCE_FILES = \
Resources/Version \


#
# Other sources
#
opensn0w_OBJC_FILES += \
	OSDFUDevice.m \
	OSDevice.m \
	OSTestSystem.m \
	OSObject.m \
	OSUSBInterface.m \
	OSBinary.m \
	OSBinaryMachO.m

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
